### ISSUE TITLE
Can't turn off led

### ISSUE THREAD

**Issue by sander151187** [jamesbarnett91/intel-nuc-led-controller#1]
Great little tool with lots of potential. I use it mailnly to impress friends atm. Would be cool if it could be linked at one time with music or video like an 'ambilight'.

However, there's one 'problem'. It doesn't supply a method to turn off the led ring, wich is a bit of a pain if you're using your NUC as a media center in a dark room.

**Comment by jamesbarnett91** [comment]
Thanks for the feedback!
Adding an option to disable the LED would be quick to implement, I'll add it to the next release.

I'm looking into adding some more automatic control modes as well, like reacting to music or maybe showing CPU usage.

**Comment by jamesbarnett91** [comment]
Added in latest build.
https://github.com/jamesbarnett91/intel-nuc-led-controller/releases/download/v0.2/NucLedController-v0.2.zip
